# Generated by Django 4.0.1 on 2022-03-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('m_frist_name', models.CharField(max_length=100)),
                ('m_last_name', models.CharField(max_length=100)),
                ('m_email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('m_password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
