# Generated by Django 4.0.1 on 2022-03-12 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
